export const FETCH_CATEGORIES = 'fetch_categories'
export const FETCH_POSTS = 'fetch_posts'
export const FETCH_POSTS_BY_CATEGORY = 'fetch_posts_by_category'
export const ADD_POST = 'add_post'
export const UPDATE_POST = 'update_post'
export const DELETE_POST = 'delete_post'